{% set name = "awscli" %}
{% set version = "2.1.38" %}

{% set botocore_pin = "2.0.0dev106" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/aws-cli/archive/refs/tags/{{ version }}.tar.gz
  patches:
    - aws-entrypoint.patch

build:
  number: 1
  noarch: python
  # https://github.com/amancevice/homebrew-core/blob/78db076bcc232c93d3df78209e72e1d6b9a358b1/Formula/awscli.rb#L47
  script: |
    {{ PYTHON }} -m pip install . --no-deps -vv
    {{ PYTHON }} scripts/gen-ac-index --include-builtin-index --index-location /tmp/ignore.ac
  entry_points:
    - aws = awscli.clidriver:main

requirements:
  host:
    - python >=3.6
    - pip
    # The build process generates the autocomplete index (scripts/gen-ac-index)
    # which requires importing awscli modules, so we need to install all runtime
    # dependencies too. YAML anchors don't support merging lists so we have to
    # duplicate everything :-(
    # Commented lines are the original requirements from
    # https://github.com/aws/aws-cli/blob/2.1.38/setup.py#L27-L37
    - botocore =={{ botocore_pin }}
    # - colorama >=0.2.5,<0.4.4
    - colorama >=0.2.5,<0.5.0
    # - docutils >=0.10,<0.16
    - docutils >=0.10,<0.18
    # - cryptography >=3.3.2,<3.4.0
    - cryptography >=3.3.2,<3.5.0
    - s3transfer >=0.3.0,<0.4.0
    # - ruamel.yaml >=0.15.0,<0.16.0
    - ruamel.yaml >=0.15.0,<0.17.0
    - wcwidth <0.2.0
    - prompt_toolkit >=2.0.0,<3.0.0
    - distro >=1.5.0,<1.6.0

  run:
    # Commented lines are the original requirements from
    # https://github.com/aws/aws-cli/blob/2.1.38/setup.py#L27-L37
    - botocore =={{ botocore_pin }}
    # - colorama >=0.2.5,<0.4.4
    - colorama >=0.2.5,<0.5.0
    # - docutils >=0.10,<0.16
    - docutils >=0.10,<0.18
    # - cryptography >=3.3.2,<3.4.0
    - cryptography >=3.3.2,<3.5.0
    - s3transfer >=0.3.0,<0.4.0
    # - ruamel.yaml >=0.15.0,<0.16.0
    - ruamel.yaml >=0.15.0,<0.17.0
    - wcwidth <0.2.0
    - prompt_toolkit >=2.0.0,<3.0.0
    - distro >=1.5.0,<1.6.0

test:
  commands:
    - aws --version
    - aws_completer
  # TODO: Check autocomplete index exists:
  #   lib/python3.x/site-packages/awscli/data/ac.index
  imports:
    - awscli
    - awscli.autocomplete
    - awscli.autoprompt
    - awscli.bcdoc
    - awscli.customizations
    - awscli.customizations.cloudformation
    - awscli.customizations.cloudtrail
    - awscli.customizations.codeartifact
    - awscli.customizations.codedeploy
    - awscli.customizations.configservice
    - awscli.customizations.configure
    - awscli.customizations.datapipeline
    - awscli.customizations.dlm
    - awscli.customizations.dynamodb
    - awscli.customizations.ec2
    - awscli.customizations.ecs
    - awscli.customizations.eks
    - awscli.customizations.emr
    - awscli.customizations.emrcontainers
    - awscli.customizations.gamelift
    - awscli.customizations.history
    - awscli.customizations.lightsail
    - awscli.customizations.logs
    - awscli.customizations.s3
    - awscli.customizations.s3.syncstrategy
    - awscli.customizations.servicecatalog
    - awscli.customizations.sso
    - awscli.customizations.wizard
    - awscli.customizations.wizard.ui
    - awscli.customizations.wizard.wizards

about:
  home: https://aws.amazon.com/cli/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: Universal Command Line Environment for AWS.
  dev_url: https://github.com/aws/aws-cli
  doc_url: https://aws.amazon.com/cli/

extra:
  recipe-maintainers:
    - manics
