name: Conda

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
      fail-fast: false
    steps:
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.1.1

      - name: Set conda-bld output folder to make it easier to find artifacts
        id: condablddir
        # On Windows /conda-bld and \\conda-bld work here but fail later
        # c:\\conda-bld seems to work.... for now
        run: |
          if [ ${{ matrix.os }} = windows-latest ]; then
            echo "condabld=c:\\conda-bld" >> $GITHUB_OUTPUT
          else
            echo "condabld=$HOME/conda-bld" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - run: |
          mkdir ${{ steps.condablddir.outputs.condabld }}
          conda config --set conda_build.output_folder ${{ steps.condablddir.outputs.condabld }}

      - name: add msys64 to path
        # needed for patch utility
        run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        if: matrix.os == 'windows-latest'

      - name: Checkout
        uses: actions/checkout@v3
      - name: Install conda build
        run: conda install -y -q conda-build conda-verify

      - name: Build
        run: conda build -c conda-forge recipe
        # Ensure $variables are expanded on Windows
        shell: bash

      - run: ls -R "${{ steps.condablddir.outputs.condabld }}"

      - uses: actions/upload-artifact@v3
        with:
          path: "${{ steps.condablddir.outputs.condabld }}/*/awscli-*"
          if-no-files-found: error

  upload:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:

      - name: setup-conda
        uses: s-weigand/setup-conda@v1.1.1
      - run: conda install -y -q anaconda-client

      - name: Download artifacts from build
        uses: actions/download-artifact@v3
      - name: List artifacts
        run: ls -R

      - name: Upload to Anaconda Cloud
        run: |
          anaconda whoami
          anaconda upload --user ${ANACONDA_USER} artifact/*/awscli*
        env:
          ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
